### ISSUE TITLE
detailed character equipment&talents

### ISSUE THREAD

**Issue by B1izzy** [twinstar-bosskills/twinstar-bosskills#60]
any chances to check historical equipment and talents at the moment of kill, not actual in armory

**Comment by mrceperka** [comment]
currently not possible. twinstar api does not provide such info.

**Comment by mrceperka** [comment]
not a priority for twinstar team right now

**Comment by mrceperka** [comment]
Closing this. Not a priority for twinstar team right now. Can't do anything about it.
